# Generated by Django 4.1.4 on 2023-01-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article_gnews',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=30)),
                ('headline', models.TextField(default='')),
                ('publish_date', models.DateField()),
                ('publish_time', models.TimeField()),
                ('source', models.TextField(default='')),
                ('article', models.TextField(default='')),
                ('url', models.TextField(default='')),
            ],
        ),
    ]
