# Generated by Django 4.1.4 on 2023-01-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_gnews',
            name='method',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='article_gnews',
            name='keyword',
            field=models.CharField(default='', max_length=30),
        ),
    ]
