# Generated by Django 4.1.4 on 2023-01-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article_gnews_method_alter_article_gnews_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_gnews',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
