# Generated by Django 4.1.4 on 2023-01-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_article_gnews_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_gnews',
            name='confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='article_gnews',
            name='sentiment',
            field=models.CharField(default='', max_length=30),
        ),
    ]
